const assert = require('assert')
const { Queue } = require('..')

describe('Queue: ', () => {
  const queue = new Queue()
  it('Queue extends EventEmitter', () => {
    assert(typeof queue.on === 'function')
    assert(typeof queue.once === 'function')
    assert(typeof queue.off === 'function')
    assert(typeof queue.emit === 'function')
    assert(typeof queue.listenerCount === 'function')
    assert(typeof queue.getMaxListeners === 'function')
    assert(typeof queue.setMaxListeners === 'function')
  })
  it('Queue should be ArrayLink', () => {
    assert(typeof queue.pop === 'function')
    assert(typeof queue.shift === 'function')
    assert(typeof queue.indexOf === 'function')
    assert(typeof queue.lastIndexOf === 'function')
    assert(typeof queue.slice === 'function')
    assert(typeof queue.reverse === 'function')
    assert(typeof queue.push === 'function')
    assert(typeof queue.unshift === 'function')
    assert(typeof queue.splice === 'function')
    assert(typeof queue.start === 'function')
    assert(typeof queue.stop === 'function')
    assert(typeof queue.end === 'function')
  })
})
